"use strict";
var karakasa_1 = require("../lib/karakasa");
var names = ["西田 健志", "西田 健志", "西田 健志", "西田 健志", "西田 健志", "西田 健志", "西田 健志", "西田 健志"];
var messages = ["消極性", "デザイン", "宣言"];
window.onload = function () {
    var examples = document.getElementById('examples');
    var h2 = document.createElement("h2");
    h2.textContent = "Names only";
    var pre = document.createElement("pre");
    pre.textContent = "createKarakasaElement(200, 200, names, 14)";
    var svg = karakasa_1.createKarakasaElement(200, 200, names, 14);
    examples.appendChild(h2);
    examples.appendChild(pre);
    examples.appendChild(svg);
    h2 = document.createElement("h2");
    h2.textContent = "With a message inside (and another with CSS rotate animation)";
    pre.textContent = "createKarakasaElement(320, 320, names, 14, messages, 24)";
    svg = karakasa_1.createKarakasaElement(320, 320, names, 14, messages, 24);
    examples.appendChild(h2);
    examples.appendChild(pre);
    examples.appendChild(svg);
    svg = karakasa_1.createKarakasaElement(320, 320, names, 14, messages, 24);
    svg.setAttribute("class", "karakasa");
    examples.appendChild(svg);
};
